# MultiMolecule
# Copyright (C) 2024-Present  MultiMolecule

# This file is part of MultiMolecule.

# MultiMolecule is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# MultiMolecule is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For additional terms and clarifications, please refer to our License FAQ at:
# <https://multimolecule.danling.org/about/license-faq>.


from multimolecule.modules import HeadConfig
from multimolecule.tokenisers import DnaTokenizer, ProteinTokenizer, RnaTokenizer

from .amplify import (
    AmplifyConfig,
    AmplifyForContactPrediction,
    AmplifyForMaskedLM,
    AmplifyForPreTraining,
    AmplifyForSequencePrediction,
    AmplifyForTokenPrediction,
    AmplifyModel,
)
from .aparent import (
    AparentConfig,
    AparentForSequencePrediction,
    AparentModel,
    AparentModelOutput,
    AparentPreTrainedModel,
)
from .aparent2 import (
    Aparent2Config,
    Aparent2ForSequencePrediction,
    Aparent2Model,
    Aparent2ModelOutput,
    Aparent2PreTrainedModel,
)
from .basenji import BasenjiBlockConfig, BasenjiConfig, BasenjiForTokenPrediction, BasenjiModel, BasenjiPreTrainedModel
from .basset import BassetConfig, BassetForSequencePrediction, BassetModel, BassetPreTrainedModel
from .bpfold import BpfoldConfig, BpfoldForRnaSecondaryStructurePrediction, BpfoldModel
from .bpnet import (
    BPNetConfig,
    BPNetEncoderOutput,
    BPNetForProfilePrediction,
    BPNetForTokenPrediction,
    BPNetHeadOutput,
    BPNetModel,
    BPNetModelOutput,
    BPNetPreTrainedModel,
    BPNetProfilePredictorOutput,
)
from .calm import (
    CaLmConfig,
    CaLmForContactPrediction,
    CaLmForMaskedLM,
    CaLmForPreTraining,
    CaLmForSequencePrediction,
    CaLmForTokenPrediction,
    CaLmModel,
)
from .chrombpnet import (
    ChromBPNetBranchOutput,
    ChromBPNetConfig,
    ChromBPNetForProfilePrediction,
    ChromBPNetForTokenPrediction,
    ChromBPNetHeadOutput,
    ChromBPNetModel,
    ChromBPNetModelOutput,
    ChromBPNetPreTrainedModel,
    ChromBPNetProfilePredictorOutput,
)
from .configuration_utils import PreTrainedConfig, validate_attention_dimensions
from .deepbind import DeepBindConfig, DeepBindForSequencePrediction, DeepBindModel, DeepBindPreTrainedModel
from .deepstarr import (
    DeepStarrConfig,
    DeepStarrForSequencePrediction,
    DeepStarrModel,
    DeepStarrModelOutput,
    DeepStarrPreTrainedModel,
)
from .dnabert import (
    DnaBertConfig,
    DnaBertForContactPrediction,
    DnaBertForMaskedLM,
    DnaBertForPreTraining,
    DnaBertForSequencePrediction,
    DnaBertForTokenPrediction,
    DnaBertModel,
)
from .dnabert2 import (
    DnaBert2Config,
    DnaBert2ForContactPrediction,
    DnaBert2ForMaskedLM,
    DnaBert2ForPreTraining,
    DnaBert2ForSequencePrediction,
    DnaBert2ForTokenPrediction,
    DnaBert2Model,
)
from .dnaberts import (
    DnaBertSConfig,
    DnaBertSForContactPrediction,
    DnaBertSForSequencePrediction,
    DnaBertSForTokenPrediction,
    DnaBertSModel,
)
from .enformer import EnformerConfig, EnformerForTokenPrediction, EnformerModel, EnformerPreTrainedModel
from .ernierna import (
    ErnieRnaConfig,
    ErnieRnaForContactPrediction,
    ErnieRnaForMaskedLM,
    ErnieRnaForPreTraining,
    ErnieRnaForSecondaryStructurePrediction,
    ErnieRnaForSequencePrediction,
    ErnieRnaForTokenPrediction,
    ErnieRnaModel,
)
from .hal import HalConfig, HalForSequencePrediction, HalModel, HalModelOutput, HalPreTrainedModel
from .hyenadna import (
    HyenaDnaConfig,
    HyenaDnaForCausalLM,
    HyenaDnaForPreTraining,
    HyenaDnaForSequencePrediction,
    HyenaDnaForTokenPrediction,
    HyenaDnaModel,
)
from .malinois import (
    MalinoisConfig,
    MalinoisForSequencePrediction,
    MalinoisModel,
    MalinoisModelOutput,
    MalinoisPreTrainedModel,
)
from .maxentscan import (
    MaxEntScanConfig,
    MaxEntScanForSequencePrediction,
    MaxEntScanModel,
    MaxEntScanPreTrainedModel,
)
from .mmsplice import (
    MmSpliceConfig,
    MmSpliceForSequencePrediction,
    MmSpliceModel,
    MmSpliceModelOutput,
    MmSpliceModuleConfig,
    MmSplicePreTrainedModel,
)
from .modeling_auto import (
    AutoModelForContactPrediction,
    AutoModelForProfilePrediction,
    AutoModelForRegulatoryProfilePrediction,
    AutoModelForRegulatorySequencePrediction,
    AutoModelForRegulatoryTrackPrediction,
    AutoModelForRegulatoryVariantEffectPrediction,
    AutoModelForRnaSecondaryStructurePrediction,
    AutoModelForSequencePrediction,
    AutoModelForSpliceSitePrediction,
    AutoModelForSpliceVariantEffectPrediction,
    AutoModelForTokenPrediction,
)
from .mtsplice import (
    MtSpliceConfig,
    MtSpliceForSequencePrediction,
    MtSpliceModel,
    MtSpliceModelOutput,
    MtSplicePreTrainedModel,
)
from .openspliceai import (
    OpenSpliceAiConfig,
    OpenSpliceAiForTokenPrediction,
    OpenSpliceAiModel,
    OpenSpliceAiPreTrainedModel,
)
from .pangolin import (
    PangolinConfig,
    PangolinForTokenPrediction,
    PangolinModel,
    PangolinModelOutput,
    PangolinModuleOutput,
    PangolinPreTrainedModel,
    PangolinStageConfig,
    PangolinTokenPredictorOutput,
)
from .procapnet import (
    ProCapNetConfig,
    ProCapNetEncoderOutput,
    ProCapNetForProfilePrediction,
    ProCapNetForTokenPrediction,
    ProCapNetHeadOutput,
    ProCapNetModel,
    ProCapNetModelOutput,
    ProCapNetPreTrainedModel,
    ProCapNetProfilePredictorOutput,
)
from .progen2 import (
    ProGen2Config,
    ProGen2ForCausalLM,
    ProGen2ForPreTraining,
    ProGen2ForSequencePrediction,
    ProGen2ForTokenPrediction,
    ProGen2Model,
)
from .ribonanzanet import (
    RibonanzaNetConfig,
    RibonanzaNetForContactPrediction,
    RibonanzaNetForDegradationPrediction,
    RibonanzaNetForPreTraining,
    RibonanzaNetForSecondaryStructurePrediction,
    RibonanzaNetForSequenceDropoutPrediction,
    RibonanzaNetForSequencePrediction,
    RibonanzaNetForTokenPrediction,
    RibonanzaNetModel,
)
from .rinalmo import (
    RiNALMoConfig,
    RiNALMoForContactPrediction,
    RiNALMoForMaskedLM,
    RiNALMoForPreTraining,
    RiNALMoForSecondaryStructurePrediction,
    RiNALMoForSequencePrediction,
    RiNALMoForTokenPrediction,
    RiNALMoModel,
)
from .rnabert import (
    RnaBertConfig,
    RnaBertForContactPrediction,
    RnaBertForMaskedLM,
    RnaBertForPreTraining,
    RnaBertForSequencePrediction,
    RnaBertForTokenPrediction,
    RnaBertModel,
)
from .rnaernie import (
    RnaErnieConfig,
    RnaErnieForContactPrediction,
    RnaErnieForMaskedLM,
    RnaErnieForPreTraining,
    RnaErnieForSequencePrediction,
    RnaErnieForTokenPrediction,
    RnaErnieModel,
)
from .rnafm import (
    RnaFmConfig,
    RnaFmForContactPrediction,
    RnaFmForMaskedLM,
    RnaFmForPreTraining,
    RnaFmForSecondaryStructurePrediction,
    RnaFmForSequencePrediction,
    RnaFmForTokenPrediction,
    RnaFmModel,
)
from .rnamsm import (
    RnaMsmConfig,
    RnaMsmForContactPrediction,
    RnaMsmForMaskedLM,
    RnaMsmForPreTraining,
    RnaMsmForSecondaryStructurePrediction,
    RnaMsmForSequencePrediction,
    RnaMsmForTokenPrediction,
    RnaMsmModel,
)
from .scbasset import ScBassetConfig, ScBassetForSequencePrediction, ScBassetModel, ScBassetPreTrainedModel
from .splicebert import (
    SpliceBertConfig,
    SpliceBertForContactPrediction,
    SpliceBertForMaskedLM,
    SpliceBertForPreTraining,
    SpliceBertForSequencePrediction,
    SpliceBertForTokenPrediction,
    SpliceBertModel,
)
from .spotrna import SpotRnaConfig, SpotRnaForRnaSecondaryStructurePrediction, SpotRnaModel
from .sptransformer import (
    SpTransformerAttentionMap,
    SpTransformerConfig,
    SpTransformerFeatureEncoderConfig,
    SpTransformerForTokenPrediction,
    SpTransformerModel,
    SpTransformerModelOutput,
    SpTransformerPreTrainedModel,
    SpTransformerTokenPredictorOutput,
)
from .ufold import UfoldConfig, UfoldForRnaSecondaryStructurePrediction, UfoldModel
from .utrbert import (
    UtrBertConfig,
    UtrBertForContactPrediction,
    UtrBertForMaskedLM,
    UtrBertForPreTraining,
    UtrBertForSequencePrediction,
    UtrBertForTokenPrediction,
    UtrBertModel,
)
from .utrlm import (
    UtrLmConfig,
    UtrLmForContactPrediction,
    UtrLmForMaskedLM,
    UtrLmForPreTraining,
    UtrLmForSecondaryStructurePrediction,
    UtrLmForSequencePrediction,
    UtrLmForTokenPrediction,
    UtrLmModel,
)
from .xpresso import (
    XpressoConfig,
    XpressoEncoderOutput,
    XpressoForSequencePrediction,
    XpressoModel,
    XpressoModelOutput,
    XpressoPreTrainedModel,
)

__all__ = [
    "PreTrainedConfig",
    "HeadConfig",
    "DnaTokenizer",
    "RnaTokenizer",
    "ProteinTokenizer",
    "AutoModelForContactPrediction",
    "AutoModelForSequencePrediction",
    "AutoModelForTokenPrediction",
    "AutoModelForProfilePrediction",
    "AutoModelForRnaSecondaryStructurePrediction",
    "AutoModelForSpliceSitePrediction",
    "AutoModelForSpliceVariantEffectPrediction",
    "AutoModelForRegulatorySequencePrediction",
    "AutoModelForRegulatoryTrackPrediction",
    "AutoModelForRegulatoryProfilePrediction",
    "AutoModelForRegulatoryVariantEffectPrediction",
    "validate_attention_dimensions",
    "AmplifyConfig",
    "AmplifyModel",
    "AmplifyForContactPrediction",
    "AmplifyForSequencePrediction",
    "AmplifyForTokenPrediction",
    "AmplifyForMaskedLM",
    "AmplifyForPreTraining",
    "AparentConfig",
    "AparentModel",
    "AparentModelOutput",
    "AparentPreTrainedModel",
    "AparentForSequencePrediction",
    "Aparent2Config",
    "Aparent2Model",
    "Aparent2ModelOutput",
    "Aparent2PreTrainedModel",
    "Aparent2ForSequencePrediction",
    "BasenjiConfig",
    "BasenjiBlockConfig",
    "BasenjiModel",
    "BasenjiPreTrainedModel",
    "BasenjiForTokenPrediction",
    "BassetConfig",
    "BassetModel",
    "BassetPreTrainedModel",
    "BassetForSequencePrediction",
    "BPNetConfig",
    "BPNetModel",
    "BPNetModelOutput",
    "BPNetEncoderOutput",
    "BPNetHeadOutput",
    "BPNetProfilePredictorOutput",
    "BPNetPreTrainedModel",
    "BPNetForProfilePrediction",
    "BPNetForTokenPrediction",
    "ChromBPNetConfig",
    "ChromBPNetModel",
    "ChromBPNetModelOutput",
    "ChromBPNetBranchOutput",
    "ChromBPNetHeadOutput",
    "ChromBPNetProfilePredictorOutput",
    "ChromBPNetPreTrainedModel",
    "ChromBPNetForProfilePrediction",
    "ChromBPNetForTokenPrediction",
    "BpfoldConfig",
    "BpfoldModel",
    "BpfoldForRnaSecondaryStructurePrediction",
    "CaLmConfig",
    "CaLmModel",
    "CaLmForContactPrediction",
    "CaLmForSequencePrediction",
    "CaLmForTokenPrediction",
    "CaLmForMaskedLM",
    "CaLmForPreTraining",
    "DeepBindConfig",
    "DeepBindModel",
    "DeepBindPreTrainedModel",
    "DeepBindForSequencePrediction",
    "DeepStarrConfig",
    "DeepStarrModel",
    "DeepStarrModelOutput",
    "DeepStarrPreTrainedModel",
    "DeepStarrForSequencePrediction",
    "DnaBertConfig",
    "DnaBertModel",
    "DnaBertForContactPrediction",
    "DnaBertForSequencePrediction",
    "DnaBertForTokenPrediction",
    "DnaBertForMaskedLM",
    "DnaBertForPreTraining",
    "DnaBert2Config",
    "DnaBert2Model",
    "DnaBert2ForContactPrediction",
    "DnaBert2ForSequencePrediction",
    "DnaBert2ForTokenPrediction",
    "DnaBert2ForMaskedLM",
    "DnaBert2ForPreTraining",
    "DnaBertSConfig",
    "DnaBertSModel",
    "DnaBertSForContactPrediction",
    "DnaBertSForSequencePrediction",
    "DnaBertSForTokenPrediction",
    "EnformerConfig",
    "EnformerModel",
    "EnformerPreTrainedModel",
    "EnformerForTokenPrediction",
    "ErnieRnaConfig",
    "ErnieRnaModel",
    "ErnieRnaForContactPrediction",
    "ErnieRnaForSequencePrediction",
    "ErnieRnaForTokenPrediction",
    "ErnieRnaForMaskedLM",
    "ErnieRnaForPreTraining",
    "ErnieRnaForSecondaryStructurePrediction",
    "HalConfig",
    "HalModel",
    "HalModelOutput",
    "HalPreTrainedModel",
    "HalForSequencePrediction",
    "HyenaDnaConfig",
    "HyenaDnaModel",
    "HyenaDnaForCausalLM",
    "HyenaDnaForPreTraining",
    "HyenaDnaForSequencePrediction",
    "HyenaDnaForTokenPrediction",
    "MalinoisConfig",
    "MalinoisModel",
    "MalinoisModelOutput",
    "MalinoisPreTrainedModel",
    "MalinoisForSequencePrediction",
    "MaxEntScanConfig",
    "MaxEntScanModel",
    "MaxEntScanPreTrainedModel",
    "MaxEntScanForSequencePrediction",
    "MmSpliceConfig",
    "MmSpliceModuleConfig",
    "MmSpliceModel",
    "MmSpliceModelOutput",
    "MmSplicePreTrainedModel",
    "MmSpliceForSequencePrediction",
    "MtSpliceConfig",
    "MtSpliceModel",
    "MtSpliceModelOutput",
    "MtSplicePreTrainedModel",
    "MtSpliceForSequencePrediction",
    "OpenSpliceAiConfig",
    "OpenSpliceAiModel",
    "OpenSpliceAiPreTrainedModel",
    "OpenSpliceAiForTokenPrediction",
    "PangolinConfig",
    "PangolinStageConfig",
    "PangolinModel",
    "PangolinModelOutput",
    "PangolinModuleOutput",
    "PangolinPreTrainedModel",
    "PangolinForTokenPrediction",
    "PangolinTokenPredictorOutput",
    "ProCapNetConfig",
    "ProCapNetModel",
    "ProCapNetModelOutput",
    "ProCapNetEncoderOutput",
    "ProCapNetHeadOutput",
    "ProCapNetProfilePredictorOutput",
    "ProCapNetPreTrainedModel",
    "ProCapNetForProfilePrediction",
    "ProCapNetForTokenPrediction",
    "SpTransformerConfig",
    "SpTransformerFeatureEncoderConfig",
    "SpTransformerModel",
    "SpTransformerModelOutput",
    "SpTransformerAttentionMap",
    "SpTransformerPreTrainedModel",
    "SpTransformerForTokenPrediction",
    "SpTransformerTokenPredictorOutput",
    "ProGen2Config",
    "ProGen2Model",
    "ProGen2ForSequencePrediction",
    "ProGen2ForTokenPrediction",
    "ProGen2ForCausalLM",
    "ProGen2ForPreTraining",
    "RibonanzaNetConfig",
    "RibonanzaNetModel",
    "RibonanzaNetForContactPrediction",
    "RibonanzaNetForSequencePrediction",
    "RibonanzaNetForTokenPrediction",
    "RibonanzaNetForPreTraining",
    "RibonanzaNetForSecondaryStructurePrediction",
    "RibonanzaNetForDegradationPrediction",
    "RibonanzaNetForSequenceDropoutPrediction",
    "RiNALMoConfig",
    "RiNALMoModel",
    "RiNALMoForContactPrediction",
    "RiNALMoForSequencePrediction",
    "RiNALMoForTokenPrediction",
    "RiNALMoForMaskedLM",
    "RiNALMoForPreTraining",
    "RiNALMoForSecondaryStructurePrediction",
    "RnaBertConfig",
    "RnaBertModel",
    "RnaBertForContactPrediction",
    "RnaBertForSequencePrediction",
    "RnaBertForTokenPrediction",
    "RnaBertForMaskedLM",
    "RnaBertForPreTraining",
    "RnaErnieConfig",
    "RnaErnieModel",
    "RnaErnieForContactPrediction",
    "RnaErnieForSequencePrediction",
    "RnaErnieForTokenPrediction",
    "RnaErnieForMaskedLM",
    "RnaErnieForPreTraining",
    "RnaFmConfig",
    "RnaFmModel",
    "RnaFmForContactPrediction",
    "RnaFmForSequencePrediction",
    "RnaFmForTokenPrediction",
    "RnaFmForMaskedLM",
    "RnaFmForPreTraining",
    "RnaFmForSecondaryStructurePrediction",
    "RnaMsmConfig",
    "RnaMsmModel",
    "RnaMsmForContactPrediction",
    "RnaMsmForSequencePrediction",
    "RnaMsmForTokenPrediction",
    "RnaMsmForMaskedLM",
    "RnaMsmForPreTraining",
    "RnaMsmForSecondaryStructurePrediction",
    "ScBassetConfig",
    "ScBassetModel",
    "ScBassetPreTrainedModel",
    "ScBassetForSequencePrediction",
    "SpotRnaConfig",
    "SpotRnaModel",
    "SpotRnaForRnaSecondaryStructurePrediction",
    "UfoldConfig",
    "UfoldModel",
    "UfoldForRnaSecondaryStructurePrediction",
    "SpliceBertConfig",
    "SpliceBertModel",
    "SpliceBertForContactPrediction",
    "SpliceBertForSequencePrediction",
    "SpliceBertForTokenPrediction",
    "SpliceBertForMaskedLM",
    "SpliceBertForPreTraining",
    "UtrBertConfig",
    "UtrBertModel",
    "UtrBertForContactPrediction",
    "UtrBertForSequencePrediction",
    "UtrBertForTokenPrediction",
    "UtrBertForMaskedLM",
    "UtrBertForPreTraining",
    "UtrLmConfig",
    "UtrLmModel",
    "UtrLmForContactPrediction",
    "UtrLmForSequencePrediction",
    "UtrLmForTokenPrediction",
    "UtrLmForMaskedLM",
    "UtrLmForPreTraining",
    "UtrLmForSecondaryStructurePrediction",
    "XpressoConfig",
    "XpressoModel",
    "XpressoEncoderOutput",
    "XpressoModelOutput",
    "XpressoPreTrainedModel",
    "XpressoForSequencePrediction",
]
