# MultiMolecule
# Copyright (C) 2024-Present  MultiMolecule

# This file is part of MultiMolecule.

# MultiMolecule is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# MultiMolecule is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# For additional terms and clarifications, please refer to our License FAQ at:
# <https://multimolecule.danling.org/about/license-faq>.


from multimolecule.modules import HeadConfig
from multimolecule.tokenisers import DnaTokenizer, ProteinTokenizer, RnaTokenizer

from .ablang import (
    AbLangConfig,
    AbLangForMaskedLM,
    AbLangForPreTraining,
    AbLangForSequencePrediction,
    AbLangForTokenPrediction,
    AbLangModel,
    AbLangPreTrainedModel,
)
from .ablang2 import (
    AbLang2Config,
    AbLang2ForContactPrediction,
    AbLang2ForMaskedLM,
    AbLang2ForPreTraining,
    AbLang2ForSequencePrediction,
    AbLang2ForTokenPrediction,
    AbLang2Model,
    AbLang2PreTrainedModel,
)
from .amplify import (
    AmplifyConfig,
    AmplifyForContactPrediction,
    AmplifyForMaskedLM,
    AmplifyForPreTraining,
    AmplifyForSequencePrediction,
    AmplifyForTokenPrediction,
    AmplifyModel,
)
from .bpfold import BpfoldConfig, BpfoldForRnaSecondaryStructurePrediction, BpfoldModel
from .calm import (
    CaLmConfig,
    CaLmForContactPrediction,
    CaLmForMaskedLM,
    CaLmForPreTraining,
    CaLmForSequencePrediction,
    CaLmForTokenPrediction,
    CaLmModel,
)
from .carp import (
    CarpConfig,
    CarpEncoderOutput,
    CarpForContactPrediction,
    CarpForMaskedLM,
    CarpForPreTraining,
    CarpForSequencePrediction,
    CarpForTokenPrediction,
    CarpModel,
    CarpModelOutput,
    CarpPreTrainedModel,
)
from .configuration_utils import PreTrainedConfig, validate_attention_dimensions
from .dnabert import (
    DnaBertConfig,
    DnaBertForContactPrediction,
    DnaBertForMaskedLM,
    DnaBertForPreTraining,
    DnaBertForSequencePrediction,
    DnaBertForTokenPrediction,
    DnaBertModel,
)
from .dnabert2 import (
    DnaBert2Config,
    DnaBert2ForContactPrediction,
    DnaBert2ForMaskedLM,
    DnaBert2ForPreTraining,
    DnaBert2ForSequencePrediction,
    DnaBert2ForTokenPrediction,
    DnaBert2Model,
)
from .dnaberts import (
    DnaBertSConfig,
    DnaBertSForContactPrediction,
    DnaBertSForSequencePrediction,
    DnaBertSForTokenPrediction,
    DnaBertSModel,
)
from .ernierna import (
    ErnieRnaConfig,
    ErnieRnaForContactPrediction,
    ErnieRnaForMaskedLM,
    ErnieRnaForPreTraining,
    ErnieRnaForSecondaryStructurePrediction,
    ErnieRnaForSequencePrediction,
    ErnieRnaForTokenPrediction,
    ErnieRnaModel,
)
from .hal import HalConfig, HalForSequencePrediction, HalModel, HalModelOutput, HalPreTrainedModel
from .hyenadna import (
    HyenaDnaConfig,
    HyenaDnaForCausalLM,
    HyenaDnaForPreTraining,
    HyenaDnaForSequencePrediction,
    HyenaDnaForTokenPrediction,
    HyenaDnaModel,
    HyenaDnaModelOutput,
)
from .maxentscan import (
    MaxEntScanConfig,
    MaxEntScanForSequencePrediction,
    MaxEntScanModel,
    MaxEntScanPreTrainedModel,
)
from .mmsplice import (
    MmSpliceConfig,
    MmSpliceForSequencePrediction,
    MmSpliceModel,
    MmSpliceModelOutput,
    MmSpliceModuleConfig,
    MmSplicePreTrainedModel,
)
from .modeling_auto import (
    AutoModelForContactPrediction,
    AutoModelForProfilePrediction,
    AutoModelForRnaSecondaryStructurePrediction,
    AutoModelForSequencePrediction,
    AutoModelForSpliceSitePrediction,
    AutoModelForSpliceVariantEffectPrediction,
    AutoModelForTokenPrediction,
)
from .mtsplice import (
    MtSpliceConfig,
    MtSpliceForSequencePrediction,
    MtSpliceModel,
    MtSpliceModelOutput,
    MtSplicePreTrainedModel,
)
from .openspliceai import (
    OpenSpliceAiConfig,
    OpenSpliceAiForTokenPrediction,
    OpenSpliceAiModel,
    OpenSpliceAiModelOutput,
    OpenSpliceAiPreTrainedModel,
    OpenSpliceAiStageConfig,
    OpenSpliceAiTokenPredictorOutput,
)
from .progen2 import (
    ProGen2Config,
    ProGen2ForCausalLM,
    ProGen2ForPreTraining,
    ProGen2ForSequencePrediction,
    ProGen2ForTokenPrediction,
    ProGen2Model,
)
from .proteinbert import (
    ProteinBertConfig,
    ProteinBertForMaskedLM,
    ProteinBertForPreTraining,
    ProteinBertForPreTrainingOutput,
    ProteinBertForSequencePrediction,
    ProteinBertForTokenPrediction,
    ProteinBertModel,
    ProteinBertModelOutput,
    ProteinBertPreTrainedModel,
)
from .ribonanzanet import (
    RibonanzaNetConfig,
    RibonanzaNetForContactPrediction,
    RibonanzaNetForDegradationPrediction,
    RibonanzaNetForPreTraining,
    RibonanzaNetForSecondaryStructurePrediction,
    RibonanzaNetForSequenceDropoutPrediction,
    RibonanzaNetForSequencePrediction,
    RibonanzaNetForTokenPrediction,
    RibonanzaNetModel,
)
from .rinalmo import (
    RiNALMoConfig,
    RiNALMoForContactPrediction,
    RiNALMoForMaskedLM,
    RiNALMoForPreTraining,
    RiNALMoForSecondaryStructurePrediction,
    RiNALMoForSequencePrediction,
    RiNALMoForTokenPrediction,
    RiNALMoModel,
)
from .rnabert import (
    RnaBertConfig,
    RnaBertForContactPrediction,
    RnaBertForMaskedLM,
    RnaBertForPreTraining,
    RnaBertForSequencePrediction,
    RnaBertForTokenPrediction,
    RnaBertModel,
)
from .rnaernie import (
    RnaErnieConfig,
    RnaErnieForContactPrediction,
    RnaErnieForMaskedLM,
    RnaErnieForPreTraining,
    RnaErnieForSequencePrediction,
    RnaErnieForTokenPrediction,
    RnaErnieModel,
)
from .rnafm import (
    RnaFmConfig,
    RnaFmForContactPrediction,
    RnaFmForMaskedLM,
    RnaFmForPreTraining,
    RnaFmForSecondaryStructurePrediction,
    RnaFmForSequencePrediction,
    RnaFmForTokenPrediction,
    RnaFmModel,
)
from .rnamsm import (
    RnaMsmConfig,
    RnaMsmForContactPrediction,
    RnaMsmForMaskedLM,
    RnaMsmForPreTraining,
    RnaMsmForSecondaryStructurePrediction,
    RnaMsmForSequencePrediction,
    RnaMsmForTokenPrediction,
    RnaMsmModel,
)
from .splicebert import (
    SpliceBertConfig,
    SpliceBertForContactPrediction,
    SpliceBertForMaskedLM,
    SpliceBertForPreTraining,
    SpliceBertForSequencePrediction,
    SpliceBertForTokenPrediction,
    SpliceBertModel,
)
from .spotrna import SpotRnaConfig, SpotRnaForRnaSecondaryStructurePrediction, SpotRnaModel
from .ufold import UfoldConfig, UfoldForRnaSecondaryStructurePrediction, UfoldModel
from .utrbert import (
    UtrBertConfig,
    UtrBertForContactPrediction,
    UtrBertForMaskedLM,
    UtrBertForPreTraining,
    UtrBertForSequencePrediction,
    UtrBertForTokenPrediction,
    UtrBertModel,
)
from .utrlm import (
    UtrLmConfig,
    UtrLmForContactPrediction,
    UtrLmForMaskedLM,
    UtrLmForPreTraining,
    UtrLmForSecondaryStructurePrediction,
    UtrLmForSequencePrediction,
    UtrLmForTokenPrediction,
    UtrLmModel,
)

__all__ = [
    "PreTrainedConfig",
    "HeadConfig",
    "DnaTokenizer",
    "RnaTokenizer",
    "ProteinTokenizer",
    "AutoModelForContactPrediction",
    "AutoModelForProfilePrediction",
    "AutoModelForSequencePrediction",
    "AutoModelForTokenPrediction",
    "AutoModelForRnaSecondaryStructurePrediction",
    "AutoModelForSpliceSitePrediction",
    "AutoModelForSpliceVariantEffectPrediction",
    "validate_attention_dimensions",
    "AbLangConfig",
    "AbLangModel",
    "AbLangPreTrainedModel",
    "AbLangForSequencePrediction",
    "AbLangForTokenPrediction",
    "AbLangForMaskedLM",
    "AbLangForPreTraining",
    "AbLang2Config",
    "AbLang2Model",
    "AbLang2PreTrainedModel",
    "AbLang2ForContactPrediction",
    "AbLang2ForSequencePrediction",
    "AbLang2ForTokenPrediction",
    "AbLang2ForMaskedLM",
    "AbLang2ForPreTraining",
    "AmplifyConfig",
    "AmplifyModel",
    "AmplifyForContactPrediction",
    "AmplifyForSequencePrediction",
    "AmplifyForTokenPrediction",
    "AmplifyForMaskedLM",
    "AmplifyForPreTraining",
    "BpfoldConfig",
    "BpfoldModel",
    "BpfoldForRnaSecondaryStructurePrediction",
    "CaLmConfig",
    "CaLmModel",
    "CaLmForContactPrediction",
    "CaLmForSequencePrediction",
    "CaLmForTokenPrediction",
    "CaLmForMaskedLM",
    "CaLmForPreTraining",
    "CarpConfig",
    "CarpModel",
    "CarpPreTrainedModel",
    "CarpModelOutput",
    "CarpEncoderOutput",
    "CarpForSequencePrediction",
    "CarpForTokenPrediction",
    "CarpForContactPrediction",
    "CarpForMaskedLM",
    "CarpForPreTraining",
    "DnaBertConfig",
    "DnaBertModel",
    "DnaBertForContactPrediction",
    "DnaBertForSequencePrediction",
    "DnaBertForTokenPrediction",
    "DnaBertForMaskedLM",
    "DnaBertForPreTraining",
    "DnaBert2Config",
    "DnaBert2Model",
    "DnaBert2ForContactPrediction",
    "DnaBert2ForSequencePrediction",
    "DnaBert2ForTokenPrediction",
    "DnaBert2ForMaskedLM",
    "DnaBert2ForPreTraining",
    "DnaBertSConfig",
    "DnaBertSModel",
    "DnaBertSForContactPrediction",
    "DnaBertSForSequencePrediction",
    "DnaBertSForTokenPrediction",
    "ErnieRnaConfig",
    "ErnieRnaModel",
    "ErnieRnaForContactPrediction",
    "ErnieRnaForSequencePrediction",
    "ErnieRnaForTokenPrediction",
    "ErnieRnaForMaskedLM",
    "ErnieRnaForPreTraining",
    "ErnieRnaForSecondaryStructurePrediction",
    "HalConfig",
    "HalModel",
    "HalModelOutput",
    "HalPreTrainedModel",
    "HalForSequencePrediction",
    "HyenaDnaConfig",
    "HyenaDnaModel",
    "HyenaDnaModelOutput",
    "HyenaDnaForCausalLM",
    "HyenaDnaForPreTraining",
    "HyenaDnaForSequencePrediction",
    "HyenaDnaForTokenPrediction",
    "MaxEntScanConfig",
    "MaxEntScanModel",
    "MaxEntScanPreTrainedModel",
    "MaxEntScanForSequencePrediction",
    "MmSpliceConfig",
    "MmSpliceModuleConfig",
    "MmSpliceModel",
    "MmSpliceModelOutput",
    "MmSplicePreTrainedModel",
    "MmSpliceForSequencePrediction",
    "MtSpliceConfig",
    "MtSpliceModel",
    "MtSpliceModelOutput",
    "MtSplicePreTrainedModel",
    "MtSpliceForSequencePrediction",
    "OpenSpliceAiConfig",
    "OpenSpliceAiStageConfig",
    "OpenSpliceAiModel",
    "OpenSpliceAiModelOutput",
    "OpenSpliceAiPreTrainedModel",
    "OpenSpliceAiForTokenPrediction",
    "OpenSpliceAiTokenPredictorOutput",
    "ProGen2Config",
    "ProGen2Model",
    "ProGen2ForSequencePrediction",
    "ProGen2ForTokenPrediction",
    "ProGen2ForCausalLM",
    "ProGen2ForPreTraining",
    "ProteinBertConfig",
    "ProteinBertModel",
    "ProteinBertPreTrainedModel",
    "ProteinBertForSequencePrediction",
    "ProteinBertForTokenPrediction",
    "ProteinBertForMaskedLM",
    "ProteinBertForPreTraining",
    "ProteinBertModelOutput",
    "ProteinBertForPreTrainingOutput",
    "RibonanzaNetConfig",
    "RibonanzaNetModel",
    "RibonanzaNetForContactPrediction",
    "RibonanzaNetForSequencePrediction",
    "RibonanzaNetForTokenPrediction",
    "RibonanzaNetForPreTraining",
    "RibonanzaNetForSecondaryStructurePrediction",
    "RibonanzaNetForDegradationPrediction",
    "RibonanzaNetForSequenceDropoutPrediction",
    "RiNALMoConfig",
    "RiNALMoModel",
    "RiNALMoForContactPrediction",
    "RiNALMoForSequencePrediction",
    "RiNALMoForTokenPrediction",
    "RiNALMoForMaskedLM",
    "RiNALMoForPreTraining",
    "RiNALMoForSecondaryStructurePrediction",
    "RnaBertConfig",
    "RnaBertModel",
    "RnaBertForContactPrediction",
    "RnaBertForSequencePrediction",
    "RnaBertForTokenPrediction",
    "RnaBertForMaskedLM",
    "RnaBertForPreTraining",
    "RnaErnieConfig",
    "RnaErnieModel",
    "RnaErnieForContactPrediction",
    "RnaErnieForSequencePrediction",
    "RnaErnieForTokenPrediction",
    "RnaErnieForMaskedLM",
    "RnaErnieForPreTraining",
    "RnaFmConfig",
    "RnaFmModel",
    "RnaFmForContactPrediction",
    "RnaFmForSequencePrediction",
    "RnaFmForTokenPrediction",
    "RnaFmForMaskedLM",
    "RnaFmForPreTraining",
    "RnaFmForSecondaryStructurePrediction",
    "RnaMsmConfig",
    "RnaMsmModel",
    "RnaMsmForContactPrediction",
    "RnaMsmForSequencePrediction",
    "RnaMsmForTokenPrediction",
    "RnaMsmForMaskedLM",
    "RnaMsmForPreTraining",
    "RnaMsmForSecondaryStructurePrediction",
    "SpotRnaConfig",
    "SpotRnaModel",
    "SpotRnaForRnaSecondaryStructurePrediction",
    "UfoldConfig",
    "UfoldModel",
    "UfoldForRnaSecondaryStructurePrediction",
    "SpliceBertConfig",
    "SpliceBertModel",
    "SpliceBertForContactPrediction",
    "SpliceBertForSequencePrediction",
    "SpliceBertForTokenPrediction",
    "SpliceBertForMaskedLM",
    "SpliceBertForPreTraining",
    "UtrBertConfig",
    "UtrBertModel",
    "UtrBertForContactPrediction",
    "UtrBertForSequencePrediction",
    "UtrBertForTokenPrediction",
    "UtrBertForMaskedLM",
    "UtrBertForPreTraining",
    "UtrLmConfig",
    "UtrLmModel",
    "UtrLmForContactPrediction",
    "UtrLmForSequencePrediction",
    "UtrLmForTokenPrediction",
    "UtrLmForMaskedLM",
    "UtrLmForPreTraining",
    "UtrLmForSecondaryStructurePrediction",
]
