# MultiMolecule
# Copyright (C) 2024-Present  MultiMolecule
#
# This file is part of MultiMolecule.
#
# MultiMolecule is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# MultiMolecule is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# For additional terms and clarifications, please refer to our License FAQ at:
# <https://multimolecule.danling.org/about/license-faq>.


# flake8: noqa

REFERENCE_CASES = [
    {
        "id": "CM009665.1_17926229-17926426",
        "sequence": "GGGCGATTATTTATAAAAAATACAAGTTTCCGCAAAGTAATAAGACGATGCATGAAATGACACCTGTCCAGTGCCAAAAGGTCAATAGAGTTGGTGACCTGATGGTAGGGGAGCCGGCGACCGATGCCTTGGTGGCCGTAACTCTAACAATCCTAAGGTAGCGAACTAAGTTCCAACCAGCAAAAAATGTAACGATCT",
        "dot_bracket": "(((((..(((.........)))..(((((((((..((((....))))..)..))))))....[[.(((..(((((((..(((...((.(((((((..((........))...))))))).))...)))))))))))(((.......))))))(...).....(........))..............]]...)).)))",
        "structural": "SSSSSMMSSSHHHHHHHHHSSSMMMMSSSSSSSIISSSSHHHHSSSSIISBBSSSSSSMMMMSSMSSSBBSSSSSSSBBSSSIIISSISSSSSSSIISSHHHHHHHHSSIIISSSSSSSISSIIISSSSSSSSSSSSSSHHHHHHHSSSSSMSHHHSMMMMMSHHHHHHHHSMMMMMMMMMMMMMMMSSMMMSSBSSS",
        "functional": "NNNNNNNNNNNNNNNNNNNNNNNNKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKNNNNNNNNNNNNNNNNNNNNKNNNNNNNNNNNNNNNNNNNNNNNNN",
    },
    {
        "id": "CP020892.1_2304657-2304448",
        "sequence": "ATCAGGGGCTCTGGAAAGAGCTTCCGGGTTGATCTCAGGCTTACCGCTCGAGTCGCCCGTGTTGTAAAAGCCCACAAGGCAGATCGACGAGATTGCGACTGGAACGAAGTTGTCCTGAGGGACGGGGAAGCGCTATCAACCGGCATGACCGTAACAGACACTGCATCGCCCAAGACATCCACGAGTCAAACGGCGAAAAATGACCCGCTC",
        "dot_bracket": ".[..((((((((....))))))))...((((...(((.(((....)).))).))))]((.(((((....(((.....))).((..((((.........................((.........))...)))).)).......))))))).......((.))...((((((((((........)))))))))))...............",
        "structural": "ESMMSSSSSSSSHHHHSSSSSSSSMMMMSSSBBBSSSBSSSHHHHSSBSSSBSSSSSSSBSSSSSMMMMSSSHHHHHSSSMSSIISSSSIIIIIIIIIIIIIIIIIIIIIIIIISSHHHHHHHHHSSIIISSSSISSMMMMMMMSSSSSSSXXXXXXXSSHSSXXXSSSSSSSSSSHHHHHHHHSSSSSSSSSSEEEEEEEEEEEEEEEE",
        "functional": "NNNNNNNNNNNNNNNNNNNNNNNNNNNKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKNNNNNNNNNNNNNNN",
    },
    {
        "id": "JACDTQ010000823.1_49400194-49400493",
        "sequence": "GGATATAGAAAAGATCTAGCTGCAAGATGCATTATCCCATTGATTCTCAAGAATATGTTCTGCTGATCTGGGTCACTTTGTTCCCTTCTTCCTTTCCTACTCAGCATTCATCCCAAAGCTGTTTGCAACACCACAAAAGCAATCTTCCAAGAGAGGGAATGTCTTTATGGCTAAGGACAAATGAGAAACTTCATTTCATTTCCTCCCTACCACATTTAAAGAATTGTGTAATTTGACTGGGAATCACTATCTATGTTTAGATAAGCATCAATTGACTTAATGTAGTAAGAAGGATTGATT",
        "dot_bracket": "......(((((.((...((....((((((((((.(((((..(((.((((...........))).)))))))..))...)))))..))))).)).))..)))))...........[[.((.....................................]].............................(((...((.((((((((((..(((((............))))))...)))))).))..)))......................(((.(((((.....))))).)))))..)))",
        "structural": "EEEEEESSSSSISSIIISSIIIISSSSSSSSSSISSSSSBBSSSBSSSSHHHHHHHHHHHSSSBSSSSSSSBBSSIIISSSSSBBSSSSSISSISSIISSSSSXXXXXXXXXXXSSHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHSSXXXXXXXXXXXXXXXXXXXXXXXXXXXXXSSSMMMSSBSSSSSSSSSSBBSSSSSHHHHHHHHHHHHSSSSSSBBBSSSSSSBSSBBSSSMMMMMMMMMMMMMMMMMMMMMMSSSISSSSSHHHHHSSSSSISSSSSBBSEE",
        "functional": "NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKK",
    },
]
