from __future__ import annotations

import importlib
import inspect
import re
from collections import defaultdict
from collections.abc import Callable
from io import StringIO
from pathlib import Path
from typing import Any

import chanfig

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "multimolecule"

DATA_README = PACKAGE_ROOT / "data" / "README.md"
DATASET_README_ROOT = PACKAGE_ROOT / "datasets"
IO_README = PACKAGE_ROOT / "io" / "README.md"
API_README = PACKAGE_ROOT / "api" / "README.md"
MODEL_README_ROOT = PACKAGE_ROOT / "models"
MODULE_README_ROOT = PACKAGE_ROOT / "modules"
RUNNER_README = PACKAGE_ROOT / "runner" / "README.md"
TOKENISER_README_ROOT = PACKAGE_ROOT / "tokenisers"
UTILS_ROOT = PACKAGE_ROOT / "utils"

GENERATED_MARKER = "<!-- This file is generated by docs/gen_pages.py. Do not edit directly. -->"
GENERATED_DOCS_DIR: Path | None = None

ACRONYM_WORDS = {
    "dna": "DNA",
    "rna": "RNA",
}

RELATIVE_DATASET_LINK = re.compile(r"(\[[^\]]+\]\()(\.?\.?/[^)#?]+)([#?][^)]*)?(\))")
README_LINK = re.compile(r"\[([^\]]+)\]\(([^):#]+)\)")

Page = tuple[str, str]
NavItem = str | dict[str, Any]
PageFactory = Callable[[], list[Page]]
NavFactory = Callable[[], dict[str, Any]]


# ---------------------------------------------------------------------------
# Markdown sources
# ---------------------------------------------------------------------------


def strip_frontmatter(lines: list[str]) -> list[str]:
    if not lines or lines[0].strip() != "---":
        return lines
    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return lines[index + 1 :]
    return lines


def frontmatter(readme: Path) -> dict[str, Any]:
    lines = readme.read_text().splitlines()
    if not lines or lines[0].strip() != "---":
        return {}

    for index, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            metadata = chanfig.load(StringIO("\n".join(lines[1:index])), method="yaml")
            if hasattr(metadata, "dict"):
                metadata = metadata.dict()
            return metadata if isinstance(metadata, dict) else {}
    return {}


def split_readme(readme: Path) -> tuple[str, str]:
    lines = strip_frontmatter(readme.read_text().splitlines())
    for index, line in enumerate(lines):
        if line.startswith("# "):
            title = line[2:].strip()
            body = "\n".join(lines[index + 1 :]).lstrip()
            return title, body
    return readme.parent.name, "\n".join(lines).lstrip()


def readme_page(readme: Path, *, rewrite_dataset_links: bool = False) -> str:
    title, body = split_readme(readme)
    if rewrite_dataset_links:
        body = rewrite_dataset_relative_links(body)
    return join_sections(f"# {title}", body)


def readme_relative_links(readme: Path) -> list[tuple[str, str]]:
    if not readme.exists():
        return []
    links = []
    for label, target in README_LINK.findall(readme.read_text()):
        if "/" in target or "." in target:
            continue
        links.append((label, target))
    return links


def rewrite_dataset_relative_links(body: str) -> str:
    known_datasets = {readme.parent.name for readme in dataset_readmes()}

    def replace(match: re.Match[str]) -> str:
        prefix, target, suffix, close = match.groups()
        suffix = suffix or ""
        dataset = target.removeprefix("./").removeprefix("../").rstrip("/")
        if dataset not in known_datasets:
            return match.group(0)
        return f"{prefix}{dataset}.md{suffix}{close}"

    return RELATIVE_DATASET_LINK.sub(replace, body)


def dataset_label(readme: Path) -> str:
    metadata = frontmatter(readme)
    title, _body = split_readme(readme)
    return str(metadata.get("pretty_name") or title)


def dataset_group(metadata: dict[str, Any]) -> tuple[str, str]:
    tags = metadata.get("tags", [])
    if isinstance(tags, list) and len(tags) >= 2:
        return str(tags[-2]), str(tags[-1])

    language = title_from_slug(str(metadata.get("language", "other")))
    return language, "Other"


def tokeniser_label(readme: Path) -> str:
    title, _body = split_readme(readme)
    return title_from_slug(title.removesuffix("Tokenizer"))


def join_sections(*sections: str) -> str:
    return "\n\n".join(section for section in sections if section)


def sort_key(label: str) -> str:
    return label.casefold()


def title_from_slug(slug: str) -> str:
    words = []
    for word in re.split(r"[-_/]+", slug):
        if not word:
            continue
        key = word.casefold()
        if key in ACRONYM_WORDS:
            words.append(ACRONYM_WORDS[key])
        elif any(character.isupper() for character in word[1:]):
            words.append(word)
        else:
            words.append(word.capitalize())
    return " ".join(words)


# ---------------------------------------------------------------------------
# Python API discovery
# ---------------------------------------------------------------------------


def object_exists(object_path: str) -> bool:
    module_path, _, object_name = object_path.rpartition(".")
    try:
        module = importlib.import_module(module_path)
    except Exception:
        return False
    return hasattr(module, object_name)


def public_object_paths(module_path: str) -> list[str]:
    try:
        module = importlib.import_module(module_path)
    except Exception:
        return []

    names = getattr(module, "__all__", None)
    if names is not None:
        return [f"{module_path}.{name}" for name in names if hasattr(module, name)]

    object_paths = []
    for name, obj in vars(module).items():
        if name.startswith("_"):
            continue
        if not (inspect.isclass(obj) or inspect.isfunction(obj)):
            continue
        if getattr(obj, "__module__", None) == module.__name__:
            object_paths.append(f"{module_path}.{name}")
    return object_paths


def python_module_pages(section: str, package_root: Path, package: str) -> list[Page]:
    pages: list[Page] = []
    readme = package_root / "README.md"
    if readme.exists():
        pages.append((f"{section}/index.md", readme_page(readme)))
    for module_file in python_module_files(package_root):
        slug = module_file.stem
        object_paths = public_object_paths(f"{package}.{slug}")
        if object_paths:
            pages.append((f"{section}/{slug}.md", api_page(title_from_slug(slug), object_paths)))
    return pages


def python_module_nav(section: str, package_root: Path, package: str) -> dict[str, list[NavItem]]:
    nav: list[NavItem] = []
    if (package_root / "README.md").exists():
        nav.append(f"{section}/index.md")
    for module_file in python_module_files(package_root):
        slug = module_file.stem
        if public_object_paths(f"{package}.{slug}"):
            nav.append({title_from_slug(slug): f"{section}/{slug}.md"})
    return {section: nav}


def python_module_files(package_root: Path) -> list[Path]:
    return [module_file for module_file in sorted(package_root.glob("*.py")) if module_file.name != "__init__.py"]


def dataset_readmes() -> list[Path]:
    return sorted(DATASET_README_ROOT.glob("*/README.md"))


def model_readmes() -> list[Path]:
    return sorted(MODEL_README_ROOT.glob("*/README.md"))


def tokeniser_readmes() -> list[tuple[str, Path]]:
    readmes = [
        (readme.parent.name, readme)
        for readme in TOKENISER_README_ROOT.glob("*/README.md")
        if (TOKENISER_README_ROOT / readme.parent.name / "ALPHABET.md").exists()
    ]
    return sorted(readmes, key=lambda item: sort_key(tokeniser_label(item[1])))


def util_entries() -> list[tuple[str, list[str]]]:
    entries = []
    for init_file in sorted(UTILS_ROOT.glob("**/__init__.py")):
        if init_file.parent == UTILS_ROOT:
            continue
        relative = init_file.parent.relative_to(UTILS_ROOT)
        slug = relative.as_posix()
        object_paths = public_object_paths(f"multimolecule.utils.{slug.replace('/', '.')}")
        if object_paths:
            entries.append((slug, object_paths))
    return sorted(entries, key=lambda entry: sort_key(title_from_slug(entry[0])))


def pipeline_entries() -> list[tuple[str, str, str]]:
    try:
        importlib.import_module("multimolecule.pipelines")
        pipelines = importlib.import_module("transformers.pipelines")
    except Exception:
        return []

    entries = []
    for slug, config in pipelines.PIPELINE_REGISTRY.supported_tasks.items():
        pipeline_class = config.get("impl")
        module = getattr(pipeline_class, "__module__", "")
        if not module.startswith("multimolecule.pipelines."):
            continue
        entries.append((slug, title_from_slug(slug), f"{module}.{pipeline_class.__name__}"))
    return sorted(entries, key=lambda entry: sort_key(entry[1]))


# ---------------------------------------------------------------------------
# Page rendering
# ---------------------------------------------------------------------------


def api_page(title: str, object_paths: list[str], body: str = "") -> str:
    api = "\n\n".join(f"::: {object_path}" for object_path in object_paths)
    return join_sections(f"# {title}", body, api)


def model_page(model: str, title: str, body: str) -> str:
    api = "\n".join(
        [
            "## API Reference",
            "",
            f"::: multimolecule.models.{model}",
            "    options:",
            "      show_root_heading: false",
            "      filters:",
            '        - "!.*Tokenizer.*"',
        ]
    )
    return join_sections(f"# {title}", body, api)


def pipeline_page(title: str, object_path: str) -> str:
    return "\n".join(
        [
            f"# {title}",
            "",
            f"::: {object_path}",
            "    options:",
            "      show_root_full_path: false",
        ]
    )


def tokeniser_page(title: str, body: str, object_path: str, alphabet_body: str) -> str:
    api = f"::: {object_path}" if object_exists(object_path) else ""
    return join_sections(f"# {title}", body, api, alphabet_body)


# ---------------------------------------------------------------------------
# Generated pages
# ---------------------------------------------------------------------------


def generated_data_pages() -> list[Page]:
    pages: list[Page] = []
    if DATA_README.exists():
        pages.append(("data/index.md", readme_page(DATA_README)))
    if object_exists("multimolecule.data.Dataset"):
        pages.append(("data/dataset.md", api_page("Dataset", ["multimolecule.data.Dataset"])))
    return pages


def generated_dataset_pages() -> list[Page]:
    pages: list[Page] = []
    datasets_readme = DATASET_README_ROOT / "README.md"
    if datasets_readme.exists():
        pages.append(("datasets/index.md", readme_page(datasets_readme)))
    pages.extend(
        (f"datasets/{readme.parent.name}.md", readme_page(readme, rewrite_dataset_links=True))
        for readme in dataset_readmes()
    )
    return pages


def generated_io_pages() -> list[Page]:
    return python_module_pages("io", IO_README.parent, "multimolecule.io")


def generated_api_pages() -> list[Page]:
    return python_module_pages("api", API_README.parent, "multimolecule.api")


def generated_module_pages() -> list[Page]:
    pages: list[Page] = []
    modules_readme = MODULE_README_ROOT / "README.md"
    if modules_readme.exists():
        pages.append(("modules/index.md", readme_page(modules_readme)))

    for label, slug in readme_relative_links(modules_readme):
        readme = MODULE_README_ROOT / slug / "README.md"
        body = split_readme(readme)[1] if readme.exists() else ""
        object_paths = public_object_paths(f"multimolecule.modules.{slug}")
        if body or object_paths:
            pages.append((f"modules/{slug}.md", api_page(label, object_paths, body)))
    return pages


def generated_runner_pages() -> list[Page]:
    return python_module_pages("runner", RUNNER_README.parent, "multimolecule.runner")


def generated_tokeniser_pages() -> list[Page]:
    pages: list[Page] = []
    tokenisers_readme = TOKENISER_README_ROOT / "README.md"
    if tokenisers_readme.exists():
        pages.append(("tokenisers/index.md", readme_page(tokenisers_readme)))

    for slug, readme in tokeniser_readmes():
        title, body = split_readme(readme)
        alphabet = TOKENISER_README_ROOT / slug / "ALPHABET.md"
        alphabet_body = split_readme(alphabet)[1] if alphabet.exists() else ""
        object_path = f"multimolecule.tokenisers.{title}"
        pages.append((f"tokenisers/{slug}.md", tokeniser_page(title, body, object_path, alphabet_body)))
    return pages


def generated_util_pages() -> list[Page]:
    return [
        (f"utils/{slug}.md", api_page(title_from_slug(slug), object_paths)) for slug, object_paths in util_entries()
    ]


def generated_model_pages() -> list[Page]:
    pages = []
    for readme in model_readmes():
        model = readme.parent.name
        title, body = split_readme(readme)
        pages.append((f"models/{model}.md", model_page(model, title, body)))
    return pages


def generated_pipeline_pages() -> list[Page]:
    return [
        (f"pipelines/{slug}.md", pipeline_page(title, object_path)) for slug, title, object_path in pipeline_entries()
    ]


PAGE_FACTORIES: tuple[PageFactory, ...] = (
    generated_data_pages,
    generated_dataset_pages,
    generated_io_pages,
    generated_api_pages,
    generated_module_pages,
    generated_runner_pages,
    generated_tokeniser_pages,
    generated_util_pages,
    generated_model_pages,
    generated_pipeline_pages,
)


def generated_pages() -> list[Page]:
    return [page for factory in PAGE_FACTORIES for page in factory()]


# ---------------------------------------------------------------------------
# Generated navigation
# ---------------------------------------------------------------------------


def generated_nav(nav: list[Any]) -> list[Any]:
    generated = []
    for item in nav:
        key = nav_key(item)
        if key in NAV_FACTORIES:
            generated.append(NAV_FACTORIES[key]())
        else:
            generated.append(item)
    return generated


def nav_key(item: Any) -> str | None:
    if isinstance(item, dict) and len(item) == 1:
        return next(iter(item))
    return None


def data_nav() -> dict[str, list[NavItem]]:
    return {"data": ["data/index.md", {"Dataset": "data/dataset.md"}]}


def api_nav() -> dict[str, list[NavItem]]:
    return python_module_nav("api", API_README.parent, "multimolecule.api")


def datasets_nav() -> dict[str, list[NavItem]]:
    readmes = {readme.parent.name: readme for readme in dataset_readmes()}
    entries = {
        slug: {dataset_label(readme): f"datasets/{slug}.md"}
        for slug, readme in sorted(readmes.items(), key=lambda item: sort_key(dataset_label(item[1])))
    }
    metadata = {slug: frontmatter(readme) for slug, readme in readmes.items()}
    groups: dict[str, dict[str, list[NavItem]]] = defaultdict(lambda: defaultdict(list))
    for slug, entry in entries.items():
        language, group = dataset_group(metadata[slug])
        groups[language][group].append(entry)

    nav: list[NavItem] = ["datasets/index.md"]
    for language in sorted(groups, key=sort_key):
        nav.append({language: [{group: groups[language][group]} for group in sorted(groups[language], key=sort_key)]})
    return {"datasets": nav}


def io_nav() -> dict[str, list[NavItem]]:
    return python_module_nav("io", IO_README.parent, "multimolecule.io")


def modules_nav() -> dict[str, list[NavItem]]:
    nav: list[NavItem] = ["modules/index.md"]
    for label, slug in sorted(
        readme_relative_links(MODULE_README_ROOT / "README.md"), key=lambda item: sort_key(item[0])
    ):
        if (MODULE_README_ROOT / slug / "README.md").exists() or public_object_paths(f"multimolecule.modules.{slug}"):
            nav.append({label: f"modules/{slug}.md"})
    return {"modules": nav}


def runner_nav() -> dict[str, list[NavItem]]:
    return python_module_nav("runner", RUNNER_README.parent, "multimolecule.runner")


def tokenisers_nav() -> dict[str, list[NavItem]]:
    return {
        "tokenisers": [
            "tokenisers/index.md",
            *({tokeniser_label(readme): f"tokenisers/{slug}.md"} for slug, readme in tokeniser_readmes()),
        ]
    }


def utils_nav() -> dict[str, list[NavItem]]:
    return {"utils": [{title_from_slug(slug): f"utils/{slug}.md"} for slug, _object_paths in util_entries()]}


def models_nav() -> dict[str, list[NavItem]]:
    languages: dict[str, list[tuple[str, dict[str, str]]]] = defaultdict(list)
    for readme in MODEL_README_ROOT.glob("*/README.md"):
        metadata = frontmatter(readme)
        title, _body = split_readme(readme)
        label = str(metadata.get("pretty_name") or title)
        language = title_from_slug(str(metadata.get("language", "other")))
        languages[language].append((sort_key(label), {label: f"models/{readme.parent.name}.md"}))

    nav: list[NavItem] = ["models/index.md"]
    for language in sorted(languages, key=sort_key):
        entries = [entry for _sort_key, entry in sorted(languages[language], key=lambda item: item[0])]
        nav.append({language: entries})
    nav.append(
        {
            "utils": [
                {"configuration_utils": "models/configuration_utils.md"},
                {"modeling_outputs": "models/modeling_outputs.md"},
            ]
        }
    )
    return {"models": nav}


def pipelines_nav() -> dict[str, list[NavItem]]:
    nav: list[NavItem] = ["pipelines/index.md"]
    nav.extend({title: f"pipelines/{slug}.md"} for slug, title, _object_path in pipeline_entries())
    return {"pipelines": nav}


NAV_FACTORIES: dict[str, NavFactory] = {
    "api": api_nav,
    "data": data_nav,
    "datasets": datasets_nav,
    "io": io_nav,
    "modules": modules_nav,
    "models": models_nav,
    "pipelines": pipelines_nav,
    "runner": runner_nav,
    "tokenisers": tokenisers_nav,
    "utils": utils_nav,
}


# ---------------------------------------------------------------------------
# MkDocs hook lifecycle
# ---------------------------------------------------------------------------


def write_generated(docs_dir: Path, path: str, content: str) -> None:
    output = docs_dir / path
    if output.exists() and not output.read_text().startswith(GENERATED_MARKER):
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(f"{GENERATED_MARKER}\n\n{content.rstrip()}\n")


def remove_generated(docs_dir: Path, path: str) -> None:
    output = docs_dir / path
    if output.exists() and output.read_text().startswith(GENERATED_MARKER):
        output.unlink()


def cleanup_generated(docs_dir: Path) -> None:
    for path, _content in generated_pages():
        remove_generated(docs_dir, path)


def on_config(config):
    global GENERATED_DOCS_DIR

    docs_dir = Path(config["docs_dir"])
    GENERATED_DOCS_DIR = docs_dir
    for path, content in generated_pages():
        write_generated(docs_dir, path, content)
    if config.get("nav"):
        config["nav"] = generated_nav(config["nav"])
    return config


def on_post_build(config):
    cleanup_generated(Path(config["docs_dir"]))


def on_build_error(error):
    if GENERATED_DOCS_DIR is not None:
        cleanup_generated(GENERATED_DOCS_DIR)
